import React,{useEffect,useState} from 'react';
import {Save,Trash2} from 'lucide-react';
import {VIEWS_KEY,SELECTED_VIEW_KEY,readViews,saveView,applyView,sameViewCriteria,readSelectedView,browserStorage} from './filter-views.js';

export default function SavedFilterViews({filters,period,setFilters,setPeriod,storageError}) {
  const [views,setViews]=useState(()=>readViews(browserStorage()));
  const [selected,setSelected]=useState(()=>readSelectedView(browserStorage(),views,{filters,period}));
  const [name,setName]=useState(()=>views.find(v=>v.id===selected)?.name||''),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{try{window.localStorage.setItem(SELECTED_VIEW_KEY,selected);}catch{setError('The selected view could not be remembered in this browser. Allow site storage.');}},[selected]);
  useEffect(()=>{const handle=e=>{if(e.key===VIEWS_KEY){setViews(readViews(window.localStorage));setSelected('');setName('');}};window.addEventListener('storage',handle);return()=>window.removeEventListener('storage',handle);},[]);
  const active=views.find(v=>v.id===selected);
  const modified=active&&!sameViewCriteria(active,{filters,period});
  const persist=next=>{try{window.localStorage.setItem(VIEWS_KEY,JSON.stringify(next));setViews(next);setError('');return true;}catch{setError('Your browser could not save the view. Allow site storage or free some space, then try again.');return false;}};
  function save(update=false){setMessage('');try{const id=update?selected:crypto.randomUUID();const next=saveView(views,{id,name,filters,period});if(persist(next)){setSelected(id);setName(name.trim());setMessage(update?'View updated.':'View saved.');}}catch(e){setError(e.message);}}
  function apply(view){const copy=applyView(view,filters);setFilters(copy.filters);setPeriod(copy.period);setSelected(view.id);setName(view.name);setError('');setMessage('View applied. Other filters replaced; your dates kept.');}
  function remove(){if(!active)return;const next=views.filter(v=>v.id!==selected);if(persist(next)){setSelected('');setName('');setMessage('View deleted. Your current filters are unchanged.');}}
  return <section className="saved-views" aria-label="Saved filter views"><div className="saved-views-title"><strong>Saved filter views</strong><span>Saved views apply your filters and time view. Dates stay independent—you can change them without deselecting the view. Saved in this browser.</span></div><div className="saved-view-buttons">{views.map(v=><button type="button" key={v.id} className={selected===v.id&&!modified?'active':''} aria-pressed={selected===v.id&&!modified} onClick={()=>apply(v)}>{v.name}</button>)}{!views.length&&<span className="muted small">Choose your filters below, enter a name and save your first view.</span>}</div><div className="saved-view-controls"><label><span>View name</span><input value={name} maxLength={80} placeholder="e.g. Marketplace fulfilled" onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();save();}}}/></label><button type="button" className="refresh" onClick={()=>save()}><Save size={15}/>Save as new</button>{active&&<><button type="button" className="logout" onClick={()=>save(true)}>Update selected</button><button type="button" className="logout" onClick={remove}><Trash2 size={15}/>Delete selected</button><span className="muted small">{modified?'Selected view has unsaved filter changes.':`Selected: ${active.name}`}</span></>}</div>{(error||storageError)&&<p className="saved-view-error" role="alert">{error||storageError}</p>}{message&&<p className="saved-view-message" role="status">{message}</p>}</section>;
}
