import React, {useEffect,useMemo,useState} from 'react';
import {RefreshCw,Download,Users,Heart,MessageCircle,Share2,FileText} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {PLATFORMS,LABELS,day,normalizeSocial,metricTotal,accountSummary,postTrend,followerTrend,csv} from './social.js';

const colors=['#511dce','#2379dd','#222b3d','#eb4680','#15a17b'];
const format=v=>v==null?'—':new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(v);
const stamp=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'short'}).format(d):'—';};
const columns=[['platform','Platform'],['published','Publish date'],['content','Content'],['likes','Likes'],['comments','Comments'],['shares','Shares'],['interactions','Interactions'],['views','Views'],['reach','Reach'],['impressions','Impressions'],['saves','Saves'],['status','Metric status'],['readAt','Metrics read at'],['url','Post URL']].map(([key,label])=>({key,label}));
function Card({title,note,children}) {return <section className="card"><div className="card-head"><div><h2>{title}</h2>{note&&<p>{note}</p>}</div></div>{children}</section>;}
function Kpi({icon:Icon,label,value,note}) {return <div className="kpi-card"><div className="kpi-icon"><Icon size={20}/></div><div><p className="eyebrow">{label}</p><h3>{format(value)}</h3><p className="kpi-note" title={note}>{note}</p></div></div>;}
function Plot({rows,series,type='bar'}) {const Chart=type==='line'?LineChart:BarChart;return rows.length?<div className="social-chart"><ResponsiveContainer width="100%" height="100%"><Chart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:10}} minTickGap={25}/><YAxis tick={{fontSize:10}}/><Tooltip/><Legend/>{series.map((s,i)=>type==='line'?<Line key={s.key} dataKey={s.key} name={s.label} stroke={s.color||colors[i]} strokeWidth={2} connectNulls={false} dot={{r:3}}/>:<Bar key={s.key} dataKey={s.key} name={s.label} fill={colors[i]} radius={[4,4,0,0]}/>)}</Chart></ResponsiveContainer></div>:<div className="empty-chart">No observations for these filters.</div>;}

export default function SocialMediaPage({onSessionExpired}) {
  const [data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [platforms,setPlatforms]=useState([...PLATFORMS]),[start,setStart]=useState(''),[end,setEnd]=useState(''),[period,setPeriod]=useState('month'),[query,setQuery]=useState(''),[metric,setMetric]=useState('all'),[sort,setSort]=useState({key:'published',dir:-1}),[page,setPage]=useState(0);
  async function load(signal) {setLoading(true);setError('');try{const response=await fetch('/api/social',{signal});if(response.status===401){onSessionExpired();return;}const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Could not load social analytics.');setData(normalizeSocial(payload));}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{if(!signal?.aborted)setLoading(false);}}
  useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[]);
  useEffect(()=>setPage(0),[platforms,start,end,query,metric,sort]);
  const posts=useMemo(()=>(data?.posts||[]).filter(r=>platforms.includes(r.platform)&&(!start||(r.date&&r.date>=start))&&(!end||(r.date&&r.date<=end))&&(!query||`${r.content} ${r.id} ${r.platform}`.toLowerCase().includes(query.toLowerCase()))&&(metric==='all'||(metric==='known'?r.interactions!==null:r.interactions===null))),[data,platforms,start,end,query,metric]);
  const accounts=useMemo(()=>accountSummary(data?.accounts||[],platforms,start,end),[data,platforms,start,end]);
  const totals=Object.fromEntries(['likes','comments','shares','interactions','views','impressions'].map(key=>[key,metricTotal(posts,key)]));
  const followers=accounts.length&&accounts.every(r=>r.followers!==null)?accounts.reduce((s,r)=>s+r.followers,0):null;
  const growth=accounts.length&&accounts.every(r=>r.growth!==null)?accounts.reduce((s,r)=>s+r.growth,0):null;
  const sorted=useMemo(()=>[...posts].sort((a,b)=>{const x=a[sort.key],y=b[sort.key];if(x==null)return y==null?0:1;if(y==null)return -1;return sort.dir*(typeof x==='number'?x-y:String(x).localeCompare(String(y)));}),[posts,sort]);
  const latest=(data?.accounts||[]).map(r=>r.captured).filter(Boolean).sort().at(-1);
  const trend=postTrend(posts,period);
  const coverage=t=>`${t.known}/${t.total} posts with data`;
  function preset(key){const today=day(new Date());if(key==='all'){setStart('');setEnd('');return;}setEnd(today);if(key==='month'){setStart(today.slice(0,7)+'-01');return;}const d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(key==='30'?29:6));setStart(d.toISOString().slice(0,10));}
  function exportPosts(){const url=URL.createObjectURL(new Blob([csv(sorted,columns)],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download='disty-social-posts.csv';link.click();URL.revokeObjectURL(url);}
  const invalid=start&&end&&start>end;
  return <div className="social-page"><div className="social-toolbar"><div><strong>Daily updates · 8–9 AM Riyadh</strong><span>Last account snapshot: {stamp(latest)} · Refresh reads the saved sheet.</span></div><button className="refresh" onClick={()=>load()} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Loading…':'Refresh social data'}</button></div>
    <section className="filter-card"><div className="filter-body"><div className="preset-row"><span>Publication dates:</span>{[['7','Last 7 days'],['30','Last 30 days'],['month','Current month'],['all','All imported posts']].map(([key,label])=><button key={key} onClick={()=>preset(key)}>{label}</button>)}</div><div className="social-filter-grid"><label className="date-field"><span>Start date (Riyadh)</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="date-field"><span>End date (Riyadh)</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="select-field"><span>Chart grouping</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></label><label className="select-field"><span>Post metric coverage</span><select value={metric} onChange={e=>setMetric(e.target.value)}><option value="all">All posts</option><option value="known">Interactions available</option><option value="missing">Awaiting / unavailable</option></select></label><label className="select-field"><span>Search posts</span><input className="social-search" placeholder="Text, platform or post ID" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="toggle-filter"><span>Platforms</span><div>{PLATFORMS.map(p=><button key={p} aria-pressed={platforms.includes(p)} className={platforms.includes(p)?'active':''} onClick={()=>setPlatforms(platforms.includes(p)?platforms.filter(v=>v!==p):[...platforms,p])}>{LABELS[p]}</button>)}<button onClick={()=>{setPlatforms([...PLATFORMS]);setStart('');setEnd('');setQuery('');setMetric('all');}}>Reset filters</button></div></div></div></section>
    {error&&<div className="inline-error" role="alert"><div><strong>Social data could not be loaded</strong><span>{error}</span></div><button onClick={()=>load()}>Retry</button></div>}
    {invalid?<div className="inline-error" role="alert">Start date must be on or before end date.</div>:!data?<div className="empty-page"><RefreshCw className={loading?'spin':''}/><h2>{loading?'Loading social analytics':'Connect your social sheet'}</h2><p>The social tab reads your synced Google Sheet through the protected dashboard connection.</p></div>:<>
    <section className="kpi-grid social-kpis"><Kpi icon={Users} label="Followers" value={followers} note="Latest snapshot on / before end date"/><Kpi icon={Users} label="Net follower growth" value={growth} note={growth===null?'Needs two snapshots per platform':accounts.some(r=>r.partial)?'Since first available snapshot':'Change from pre-period baseline'}/><Kpi icon={FileText} label="Published posts" value={posts.length} note="Imported posts matching filters"/><Kpi icon={Heart} label="Interactions" value={totals.interactions.value} note={coverage(totals.interactions)}/><Kpi icon={Heart} label="Likes" value={totals.likes.value} note={coverage(totals.likes)}/><Kpi icon={MessageCircle} label="Comments" value={totals.comments.value} note={coverage(totals.comments)}/><Kpi icon={Share2} label="Shares" value={totals.shares.value} note={coverage(totals.shares)}/><Kpi icon={FileText} label="Views" value={totals.views.value} note={coverage(totals.views)}/></section>
    <div className="social-note">Post filters use publication date. Likes, comments, shares and views are cumulative values as of each post’s last metric read; they are not engagement earned within the selected dates. “—” means unavailable. Followers use date and platform filters only. Growth is net change, including unfollows; history starts with your first snapshot.</div>
    <div className="two-col"><Card title="Publishing activity" note={`Imported posts by ${period}`}><Plot rows={trend} series={[{key:'posts',label:'Published posts'}]}/></Card><Card title="Post engagement" note="Cumulative interactions grouped by publication date; partial coverage"><Plot rows={trend} series={[{key:'interactions',label:'Known interactions'}]} type="line"/></Card></div>
    <Card title="Follower history" note="Daily observations, without filling missing days"><Plot rows={followerTrend(data.accounts,platforms,start,end)} series={platforms.map(p=>({key:p,label:LABELS[p],color:colors[PLATFORMS.indexOf(p)]}))} type="line"/></Card>
    <Card title="Platform comparison" note="Follower snapshots and imported post performance"><div className="table-wrap"><table><thead><tr>{['Platform','Followers','Snapshot date','Net growth','Growth baseline','Posts','Likes','Comments','Shares','Interactions','Coverage'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{accounts.map(a=>{const rows=posts.filter(r=>r.platform===a.platform);return <tr key={a.platform}><td>{LABELS[a.platform]}</td><td>{format(a.followers)}</td><td>{a.date||'—'}</td><td>{format(a.growth)}</td><td>{a.baseline||'—'}</td><td>{rows.length}</td>{['likes','comments','shares','interactions'].map(key=><td key={key}>{format(metricTotal(rows,key).value)}</td>)}<td>{coverage(metricTotal(rows,'interactions'))}</td></tr>;})}</tbody></table></div></Card>
    <section className="card"><div className="card-head"><div><h2>Post analytics</h2><p>{posts.length} matching posts · Click a heading to sort</p></div><button className="logout" onClick={exportPosts}><Download size={16}/>Export filtered CSV</button></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key} aria-sort={sort.key===c.key?(sort.dir===1?'ascending':'descending'):'none'}><button className="social-sort" onClick={()=>setSort({key:c.key,dir:sort.key===c.key?-sort.dir:-1})}>{c.label}{sort.key===c.key?(sort.dir===1?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{sorted.slice(page*15,page*15+15).map(r=><tr key={`${r.platform}:${r.id}`}>{columns.map(c=><td key={c.key} className={c.key==='content'?'social-content':''}>{c.key==='platform'?LABELS[r.platform]:c.key==='content'?<span dir="auto" title={r.content}>{r.content}</span>:c.key==='url'?(/^https:\/\//i.test(r.url)?<a href={r.url} target="_blank" rel="noopener noreferrer">Open post ↗</a>:'—'):['published','readAt'].includes(c.key)?stamp(r[c.key]):typeof r[c.key]==='number'||r[c.key]===null?format(r[c.key]):r[c.key]||'—'}</td>)}</tr>)}</tbody></table>{!posts.length&&<div className="table-empty">No posts match these filters.</div>}</div><div className="pagination"><span>Page {page+1} of {Math.max(1,Math.ceil(posts.length/15))}</span><div><button aria-label="Previous page" disabled={!page} onClick={()=>setPage(page-1)}>‹</button><button aria-label="Next page" disabled={(page+1)*15>=posts.length} onClick={()=>setPage(page+1)}>›</button></div></div></section>
    <Card title="Sync status" note="Most recent saved operations; archive coverage depends on the provider"><div className="table-wrap"><table><thead><tr><th>Time (Riyadh)</th><th>Service</th><th>Status</th><th>Details</th></tr></thead><tbody>{[...data.logs].reverse().slice(0,20).map((r,i)=><tr key={i}><td>{stamp(r.time)}</td><td>{r.service}</td><td>{r.status}</td><td className="social-log">{r.details}</td></tr>)}</tbody></table></div></Card>
    </>}
  </div>;
}
